INSERT OR IGNORE INTO categories(name, slug, sort_order) VALUES
('Hollywood','hollywood',10),
('Bollywood','bollywood',20),
('Bangla','bangla',30),
('South Indian','south-indian',40),
('Korean','korean',50),
('Japanese','japanese',60),
('Animation','animation',70),
('Action','action',80),
('Thriller','thriller',90),
('Horror','horror',100),
('Sci-Fi','sci-fi',110),
('Drama','drama',120),
('Comedy','comedy',130),
('Romance','romance',140),
('Mystery','mystery',150),
('Crime','crime',160),
('Fantasy','fantasy',170),
('Web Series','web-series',180);
